### ISSUE TITLE
Perhaps elaborate on necessity of ProxyCrate

### ISSUE THREAD

**Issue by JustAPerson** [denzp/rust-ptx-builder#2]
It seems confusing that the actual ptx file is generated somewhere in `/tmp/` instead of the path given to `Builder::new()`. Could you explain more in the README? Is this permanent?

**Comment by denzp** [comment]
The "feature" was introduced during quite recently. 

Originally, the PTX assembly was created just inside of `{CRATE_PATH}/target/nvptx64-nvidia-cuda` (which I believe you expect to have) by [ptx-linker](https://github.com/denzp/rust-ptx-linker). The approach required to have a PTX crate as **dylib**:
```
[lib]
crate_type = ["dylib"]
```
------

After first successful attempts, I realized that we can go further, and have CUDA and Host code inside one crate. This was impossible to achieve because we can't conditionally switch `crate_type`, and then idea with proxy crate came. 

Also, another frontier that blocked mixed code in one crate, is that several cargo sessions were trying to lock on `{CRATE_PATH}/target/nvptx64-nvidia-cuda`. This was happening because we run Host build, which invoke PTX build (via `build.rs` script), but the latter was unable to lock on already locked `target` directory. This was causing a "build deadlock".

-----

Proxy crate "feature", solved both problems, though. First, we didn't need to set `crate_type` implicitly, because it has been done at the proxy crate. And second, build processes were acquiring locks for different `target` directories, and therefore no more deadlocking happened.

Btw, you might find useful approach with [build environment variable](https://github.com/denzp/rust-inline-cuda-tutorial/blob/master/chapter-1/host/build.rs#L21) and [`include_str!`](https://github.com/denzp/rust-inline-cuda-tutorial/blob/master/chapter-1/host/src/static_cuda.rs#L43), where you don't need to worry about location or ship PTX assembly alongside with your application. Let Rust handle this, and store the assembly as `&'static str` automatically.

Thanks for reporting, I'll update a README with details soon!
